export const ROUTE_NAMES = {
  HOME: 'home',
  PRODUCT_LIST: 'product-list',
  ACTIVITY_PRODUCTS: 'activity-products',
  ACTIVITY_LIST: 'activity-list',
  WORK_LIST: 'work-list',
  WORK_ACTIVITIES: 'work-activities',
  CART: 'cart',
  CHECKOUT: 'checkout',
  ORDER_LIST: 'order-list',
  ORDER_DETAIL: 'order-detail',
  LOGIN: 'login',
  LINE_CALLBACK: 'line-callback',
  LINE_ADD_FRIEND: 'line-add-friend',
  MEMBER_PROFILE: 'member-profile',
  MEMBER_ADDRESS_BOOK: 'member-address-book',
  PURCHASE_NOTICE: 'purchase-notice',
  PRIVACY_POLICY: 'privacy-policy',
  TERMS: 'terms',
  USER_GUIDE: 'user-guide'
};
